language: c
compiler:
  - gcc
  - clang

script: ./build-test.sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev libsdl1.2-dev libvorbis-dev libfreetype6-dev mingw32
  
notifications:
  irc: "irc.freenode.org#ioquake3"
